export const SEND_CERTIFICATE_MAIL_REQUEST = 'SEND_CERTIFICATE_MAIL_REQUEST';
export const SEND_CERTIFICATE_MAIL_SUCCESS = 'SEND_CERTIFICATE_MAIL_SUCCESS';
export const SEND_CERTIFICATE_MAIL_FAIL = 'SEND_CERTIFICATE_MAIL_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";